"""add status

Revision ID: 232dc9b72c94
Revises: ead6185f9343
Create Date: 2025-09-10 21:30:45.334827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '232dc9b72c94'
down_revision = 'ead6185f9343'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
