"""empty message

Revision ID: 578c41c0c90b
Revises: 6cb1751ea35e
Create Date: 2025-09-04 01:25:41.069144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '578c41c0c90b'
down_revision = '6cb1751ea35e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apartment', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('hora', sa.DateTime(), nullable=False))
        batch_op.drop_constraint('reservation_email_key', type_='unique')
        batch_op.drop_constraint('reservation_type_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.create_unique_constraint('reservation_type_key', ['type'])
        batch_op.create_unique_constraint('reservation_email_key', ['email'])
        batch_op.drop_column('hora')
        batch_op.drop_column('phone')
        batch_op.drop_column('description')
        batch_op.drop_column('apartment')

    # ### end Alembic commands ###
