"""empty message

Revision ID: 8da17ecd1310
Revises: 578c41c0c90b
Create Date: 2025-09-06 05:40:11.179434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8da17ecd1310'
down_revision = '578c41c0c90b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reservationpacking', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('reservationbbq', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_column('reservationbbq')
        batch_op.drop_column('reservationpacking')

    # ### end Alembic commands ###
