"""empty message

Revision ID: f8eca9b435e3
Revises: 6ce92246c927
Create Date: 2025-09-03 03:28:01.965927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8eca9b435e3'
down_revision = '6ce92246c927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hora', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')))
        batch_op.drop_constraint('reservation_email_key', type_='unique')
    # ...existing code...
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.create_unique_constraint('reservation_email_key', ['email'])
        batch_op.drop_column('hora')

    # ### end Alembic commands ###
